apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-web
  template:
    metadata:
      labels:
        app: front-web
    spec:
      containers:
      - name: front-web
        image: oierur05/as-laboratorio-8-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
