name: Run Tests and Linting

on:
  push:
    branches:
      - '*'
    # Excluimos la rama 'main' para que no ejecute en esa rama
    # Podrías agregar más ramas si es necesario:
    # - 'feature/*'  

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar código
        uses: actions/checkout@v4
      - name: Analizar código
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint

