name: Workflow test labo 8

on: 
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar código
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # Usamos el PAT como token

      - name: Analizar código
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
