name: Workflow test labo 8

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Bajar código
        uses: actions/checkout@v4
      - name: Analizar código
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
